Fix visual errors
BarApp-Chort-Quarin-Reynoso/BarApp-Mobile pull request #81
Opened 2024-10-14 22:05 UTC by Valenreynoso17

2024-10-14 22:09 UTC, ChortJulio commented on app/src/main/java/com/barapp/ui/loginSignup/PantallaOlvidePassword.kt
> +                        Timber.d("Se ha enviado el mail de reseteo de password")
Podrían estar en el string.xml

2024-10-14 22:10 UTC, ChortJulio commented on app/src/main/res/values/strings.xml
> +    <!-- TODO: Remove or change this placeholder text -->
???

2024-10-14 22:10 UTC, ChortJulio commented on app/src/main/res/values/strings.xml
> -    <string name="placeholder_telefono_argentina">"+54 %1$s"</string>
che seguro que esto no rompe nada?

2024-10-14 22:13 UTC, ChortJulio requested changes

2024-10-14 22:13 UTC, ChortJulio commented on app/src/main/res/layout/fragment_pantalla_olvide_password.xml
> +                    android:text="Enviar mail"
strings.xml

2024-10-14 22:13 UTC, ChortJulio commented on app/src/main/res/layout/fragment_pantalla_olvide_password.xml
> +                    android:text="¿Has olvidado tu contraseña? Ingresa tu dirección de correo y te enviaremos un mail para que puedas restablecer tus credenciales."
strings.xml

2024-10-14 22:13 UTC, ChortJulio commented on app/src/main/res/layout/fragment_pantalla_olvide_password.xml
> +                    android:text="Olvidé mi contraseña"
strings.xml

2024-10-14 22:13 UTC, ChortJulio commented on app/src/main/res/layout/fragment_pantalla_mi_cuenta.xml
> -            app:prefixText="+54"
MMMM no sé si podes quitar esto así nomás @FedericoQuarin qué opinás?

2024-10-14 22:13 UTC, ChortJulio commented on app/src/main/res/layout/fragment_login.xml
> +            android:text="@string/olvid_la_contrase_a"
muy feo el nombre del string, aparte que el contentDescription debería tener otro diferente

2024-10-14 22:13 UTC, ChortJulio commented on app/src/main/java/com/barapp/ui/pantallas/PantallaResumenReserva.kt
> +      binding.textViewTelefono.text = usuario.detalleUsuario?.telefono
Ver otros comentarios, no sé si podés quitarlo así como así porque se usa banda ese '+54'

2024-10-14 22:17 UTC, Valenreynoso17 commented on app/src/main/java/com/barapp/ui/pantallas/PantallaResumenReserva.kt
> +      binding.textViewTelefono.text = usuario.detalleUsuario?.telefono
porque en todas las que se usa se usa y se ve mal

2024-10-15 00:13 UTC, FedericoQuarin approved these changes
Chupala julio

2024-10-15 00:14 UTC, merged